name: Keep Streamlit Alive

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request to Streamlit app
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://stock-risk-adjusted-screener.streamlit.app/